# datasource connection properties
spring.datasource.url=${NEON_DB_URL}
spring.datasource.name=cashtran
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
server.address=0.0.0.0

cashtran.frontend.url=http://localhost:5173

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.header=Authorization
jwt.base64-secret=${JWT_BASE64_SECRET}
jwt.expiration=604800
jwt.token-validity-in-seconds=86400
jwt.token-validity-in-seconds-for-remember-me=108000
jwt.route.authentication.path=/login
jwt.route.authentication.refresh=/refresh

server.error.include-message=always
server.error.include-stacktrace=always

# email
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:username}
spring.mail.password=${MAIL_PASSWORD:password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.test-connection=false

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.writetimeout=5000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.roles=
management.health.mail.enabled=false